version: "3.9"
services:
  instantsplat:
    image: docker_instantsplat
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/ivm/instantsplat_dev:/home/smith/instantsplat_dev
    tty: true


